version: "3.9"

services:
  database:
    image: postgres:15.1-alpine
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: teashop
    volumes:
      - ./db-data:/var/lib/postgresql/data
